config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  devise_for :users
  get 'home/download_sample_csv'
  get 'home/sample'
  resources :students do
    collection do
      get :import
      post :upload
    end
  end    
  root 'home#index'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/import.rb
class Import < ApplicationRecord
  has_attached_file :file
  validates_attachment_content_type :file , :content_type => 'text/csv'
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true,
             :optional => true

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/student.rb
class Student < ApplicationRecord
  require 'my_file_util'
  def self.upload_csv file
   spreadsheet = MyFileUtil.open_file(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
        params = { name: row["name".strip()], 
                   address: row["address".strip()],
                   father_name: row["father_name".strip()],
                   degree: row["degree".strip()]
                  }
        student = Student.find_or_create_by( name: params[:name], address: params[:address])
        student.update_attributes(params)
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  after_create :assign_default_role
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  def assign_default_role
    self.add_role(:user) if self.roles.blank?
  end
end
   

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  require 'csv'
   respond_to :html, :json,:csv
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  def authenticated_user
    if current_user
      current_user
    else
      'Gourav lele'
    end
  end
  protected
    def configure_permitted_parameters
      added_attrs = [:username, :email,:mobile_no, :password, :password_confirmation, :remember_me,:avatar]
      devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
      devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
  def index

  end

  def download_sample_csv
    respond_to do |format|
      format.csv { render text: sample}
    end
  end

  def sample
    CSV.generate do |csv|
      csv << ["name", "address", "father_name", "degree"]
    end  
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  require 'my_file_util'
  def index
    
  end
  def create
    
  end
  def import

  end
  def upload
    if current_user.has_role? :admin
      @import_file = Import.create(file: params[:file])
      UploadWorker.perform_async(@import_file.id)
    else
      spreadsheet = MyFileUtil.open_file(params[:file])
      if spreadsheet.last_row > 1000
        flash[:alert] = "Not Authorized!!!"
        render :action => :import
      else
        @import_file = Import.create(file: params[:file])
        UploadWorker.perform_async(@import_file.id)
      end  
    end    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/students_helper.rb
module StudentsHelper
  def fetch_categories
    students =  $redis.get("students")
    if students.nil?
      students = Student.all.to_json
      $redis.set("Degree", students)
    end
    @students = JSON.load students
  end
end

app/views/home/index.html.erb
<%= link_to "Import Details",import_students_path %>
<%= link_to "Show Students", students_path%>
<%= link_to "Logout", destroy_user_session_path , method: :delete%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container-fluid"  style="padding-left: 0px; padding-right: 0px;">
      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/students/import.html.erb
<%= form_tag upload_students_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/students/index.html.erb
<%= fetch_categories.each do |student|%>
<%end%>	